name: Test with Docker CI

on:
  push:
    branches: [ feat/add-test-action ]
  pull_request:
    branches: [ feat/add-test-action ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag fosslight_web:1.0.0 .
    - name: Docker run
      run: docker run -d -p 8180:8180 --name fosslight_web fosslight_web:1.0.0
