name: Test with Docker CI

on:
  push:
    branches: [ feat/add-test-action ]
  pull_request:
    branches: [ feat/add-test-action ]

jobs:
  test:

    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10
        # volumes:
        #   - ./db/conf.d:/etc/mysql/conf.d
        #   - ./db/data:/var/lib/mysql
        #   - ./db/initdb.d:/docker-entrypoint-initdb.d
        env:
          MYSQL_DATABASE: fosslight
          MYSQL_PASSWORD: fosslight
          MYSQL_USER: fosslight
          MYSQL_ROOT_PASSWORD: fosslight
        ports:
          - 3306:3306

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --tag fosslight_web:1.0.0 .

    - name: Docker run
      run: docker run -d -p 8180:8180 --name fosslight_web fosslight_web:1.0.0

    - name: Publish test results
      uses: EnricoMi/publish-unit-test-result-action@v1
      if: ${{ always() }}
      with:
        files: build/test-results/**/*.xml