name: Test with Docker CI

on:
  push:
    branches: [ feat/add-test-action ]

jobs:
  integration-test-with-docker:
    runs-on: ubuntu-latest

    services:
      db:
        image: mariadb:10
        env:
          MYSQL_DATABASE: fosslight
          MYSQL_PASSWORD: fosslight
          MYSQL_USER: fosslight
          MYSQL_ROOT_PASSWORD: fosslight
        ports:
          - 3306:3306
        options: -v ${{ github.workspace }}/db/conf.d:/etc/mysql/conf.d
                 -v ${{ github.workspace }}/db/data:/var/lib/mysql
                 -v ${{ github.workspace }}/db/initdb.d:/docker-entrypoint-initdb.d
                 --name="fosslight_db"
                 --health-cmd="mysqladmin ping"
                 --health-interval=10s
                 --health-timeout=5s
                 --health-retries=3

    steps:
      - name: Give permission
        run: sudo chown -R $USER:$USER /home/runner/work/fosslight/fosslight

      - uses: actions/checkout@v2

      - name: Restart db container
        run: docker restart fosslight_db

      - name: Check if init.sql exists in db container
        run: docker exec fosslight_db ls -la ./docker-entrypoint-initdb.d/

      - name: check pwd
        run: pwd

      # - name: Check DB schema
      #   run: docker exec -i fosslight_db mysql -ufosslight -pfosslight -e "show databases; use fosslight; show tables;"

      - name: Check running containers
        run: docker ps

      # - name: Build docker image
      #   run: docker build -t fosslight_web .