name: Test with Docker CI

on:
  push:
    branches: [ feat/add-test-action ]
  pull_request:
    branches: [ feat/add-test-action ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
